Poprawa
t0meck-pj/ukos2023-24_13c pull request #30
Opened 2023-12-15 21:51 UTC by s30310-pj

2023-12-15 23:53 UTC, t0meck-pj requested changes
Do poprawy te ^D

2023-12-15 23:53 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia2/2.txt
> +odczytu nie mogę wejść do żadnego katalogu. Bez problemu jestem w stanie usunąć
Bez uprawnień do odczytu wejść do katalogu?
yyy... coś tu nie tak. Do poprawy.

2023-12-15 23:53 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia2/2.txt
> +        -jedynie do plików/katalogów do których mamy co najmniej uprawnienia do
Jesteśmy w stanie wykonać `cd` do pliku?
I ponadto potrzebujemy mieć uprawnienia do oczytu?
Do poprawy.

2023-12-15 23:53 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia3/3_3.txt
> +    -zakończyło się wykonywanie komendy cat, program wypisał komunikat "^C"
To nie program tylko `bash` w konsoli wstawił tekstową reprezentację tejże kombinacji.

2023-12-15 23:53 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia3/3_3.txt
> +    -CTRL+C natychmiastowo zabija obecnie wykonywany proces, a CTRL+D wychodzi
^D nie wychodzi z procesu, nie zabija go i nie kończy. Fakt zakończenia się procesu wynika z końca danych wchodzących a nie z jego zabicia. Program nie ma więcej nic do przetworzenia więc kończy pracę ale po przetworzeniu wpisanych danych. Ponadto program nie zapisuje nic do pliku tylko na swoje standardowe wyjście, które to dopiero przez basha w którym jest uruchomiony proces jest przekierowywane do pliku.

2023-12-15 23:53 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia3/3_3.txt
> +     kończy obecny proces
Nie. Nie kończy.

2024-02-02 18:56 UTC, t0meck-pj requested changes

2024-02-02 18:56 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia2/2.txt
> +        -jedynie do plików/katalogów do których mamy co najmniej uprawnienia do
Wciąż do poprawy

2024-02-02 18:56 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia3/3_3.txt
> +	CTRL+D zapisuje treść na swoim standardowym wyjściu
^D nic nie zapisuje. To także nie ma żadnego wyjścia. Brak zrozumienia materiału.
Do poprawy.

2024-02-02 20:08 UTC, s30310-pj commented
pt., 2 lut 2024 o 19:56 t0meck-pj ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In s30310-KacperKoszelak/zajecia3/3_3.txt
> <https://github.com/t0meck-pj/ukos2023-24_13c/pull/30#discussion_r1476542300>
> :
>
> >
>  3.DLACZEGO się różnią?
> -    -CTRL+C natychmiastowo przerywa wykonywanie programu, CTRL+D zwraca tekst z
> -    programu i go kończy
> +    -Oba skróty mają inne zastosowania, CTRL+C służy do zabicia procesu, a
> +	CTRL+D zapisuje treść na swoim standardowym wyjściu
>
> ^D nic nie zapisuje. To także nie ma żadnego wyjścia. Brak zrozumienia
> materiału.
> Do poprawy.
> ------------------------------
>
> In s30310-KacperKoszelak/zajecia2/2.txt
> <https://github.com/t0meck-pj/ukos2023-24_13c/pull/30#discussion_r1476540574>
> :
>
> > @@ -25,7 +29,8 @@ usuwając wszelkie uprawnienia dostępu do katalogu nadrzędnego (nadkatalogu).
>      -chmod -rwx katalog1
>
>      W jakich przypadkach możemy wykonać wtedy polecenie cd ?
> -        -jedynie do plików/katalogów do których mamy uprawnienia
> +        -jedynie do plików/katalogów do których mamy co najmniej uprawnienia do
>
> Wciąż do poprawy
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/t0meck-pj/ukos2023-24_13c/pull/30#pullrequestreview-1860099412>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BC55PTDHM5JOLHNCZRIMT3LYRUZE3AVCNFSM6AAAAABAXBAYSSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRQGA4TSNBRGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-02 20:26 UTC, t0meck-pj requested changes

2024-02-02 20:26 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia2/2.txt
> +        -jedynie do plików/katalogów do których mamy uprawnienia dostępu
Wciąż do poprawy.
Jeszcze raz:

Jak chcesz zrobić `cd` do pliku?

2024-02-02 20:26 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia3/3_3.txt
> +	CTRL+D kończy program
CTRL+D NIE KOŃCZY PROGRAMU!
CTRL+D jedyne co robi to kończy/zamyka strumień wejściowy i daje programowi informację o tym, że więcej danych nie będzie a co program z tym zrobi to już skrótu CTRL+D kompletnie nie obchodzi.

2024-02-02 21:16 UTC, s30310-pj commented
pt., 2 lut 2024 o 21:26 t0meck-pj ***@***.***> napisał(a):

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In s30310-KacperKoszelak/zajecia2/2.txt
> <https://github.com/t0meck-pj/ukos2023-24_13c/pull/30#discussion_r1476693614>
> :
>
> > @@ -25,7 +30,7 @@ usuwając wszelkie uprawnienia dostępu do katalogu nadrzędnego (nadkatalogu).
>      -chmod -rwx katalog1
>
>      W jakich przypadkach możemy wykonać wtedy polecenie cd ?
> -        -jedynie do plików/katalogów do których mamy uprawnienia
> +        -jedynie do plików/katalogów do których mamy uprawnienia dostępu
>
> Wciąż do poprawy.
> Jeszcze raz:
>
> Jak chcesz zrobić cd do pliku?
> ------------------------------
>
> In s30310-KacperKoszelak/zajecia3/3_3.txt
> <https://github.com/t0meck-pj/ukos2023-24_13c/pull/30#discussion_r1476694633>
> :
>
> >
>  3.DLACZEGO się różnią?
> -    -CTRL+C natychmiastowo przerywa wykonywanie programu, CTRL+D zwraca tekst z
> -    programu i go kończy
> +    -Oba skróty mają inne zastosowania, CTRL+C służy do zabicia procesu, a
> +	CTRL+D kończy program
>
> CTRL+D NIE KOŃCZY PROGRAMU!
> CTRL+D jedyne co robi to kończy/zamyka strumień wejściowy i daje
> programowi informację o tym, że więcej danych nie będzie a co program z tym
> zrobi to już skrótu CTRL+D kompletnie nie obchodzi.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/t0meck-pj/ukos2023-24_13c/pull/30#pullrequestreview-1860331984>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BC55PTB5XLPBORMLYQXAIT3YRVDWXAVCNFSM6AAAAABAXBAYSSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRQGMZTCOJYGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-04 03:53 UTC, t0meck-pj approved these changes

2024-02-04 03:53 UTC, t0meck-pj commented on s30310-KacperKoszelak/zajecia2/2.txt
> +        -jedynie do plików/katalogów do których mamy uprawnienia dostępu i bezpośrednią ścieżkę
Ile razy mam powtarzać by poprawić tę konkretną linijkę?!
DO PLIKU NIE DA SIĘ WEJŚĆ. Więc notacja "plików/katalogów" jest tu błędna.
Do poprawy!

2024-02-04 03:53 UTC, merged